### ISSUE TITLE
Tooltip not visible.

### ISSUE THREAD

**Issue by anupkale1984** [jonrh/react-native-highcharts-demo#1]
When i see on simulator, i am able to see tooltip as expected on cursor click. But when with same build on device i touch , pint gets highlighted but does not show any tooltip.

**Comment by jonrh** [comment]
Hi Anup, thank you for filing the issue. This repository is only for constructing various demos while using the react-native-highcharts library. I see you have created the [same issue in the correct place](https://github.com/TradingPal/react-native-highcharts/issues/36). I will therefore close this issue. I hope it gets resolved swiftly, wish you a great weekend.
